package inventory

import (
    "matrix/smith"
    "matrix/smith/fieldtype"
)

var StockEntity = smith.Entity{
    ModuleTitleName     : "Inventory",
    ModuleLowerCase     : "inventory",
    ModuleChinese       : "仓储管理",
    EntityTitleName     : "Stock",
    EntityCamelCase     : "stock",
    EntityChinese       : "仓库",
    TableName           : "stock",
    TablePrefix         : "hd_inventory_",

    FieldList: []smith.Field{
        smith.Field{
            VerboseName : "编号",
            Name        : "Code",
            Column      : "stock_code",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : "true",
            Index       : true,
            Null        : false,
            Blank       : false,
            Min         : "3",
            Max         : "10",
        },
        smith.Field{
            VerboseName : "名称",
            Name        : "Name",
            Column      : "stock_name",
            FieldType   : fieldtype.NVarchar,
            Length      : 255,
            Precision   : 0,
            Scale       : 0,
            Unique      : "true",
            Index       : true,
            Null        : false,
            Blank       : false,
            Min         : "3",
            Max         : "30",
        },
        smith.Field{
            VerboseName : "仓库地址",
            Name        : "Address",
            Column      : "address",
            FieldType   : fieldtype.NVarchar,
            Length      : 300,
            Precision   : 0,
            Scale       : 0,
            Unique      : "false",
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "3",
            Max         : "20",
        },
        smith.Field{
            VerboseName : "负责人",
            Name        : "Keeper",
            Column      : "keeper",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : "false",
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "",
            Max         : "20",
        },
        smith.Field{
            VerboseName : "联系电话",
            Name        : "Phone",
            Column      : "phone",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : "false",
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "2",
            Max         : "40",
        },
        smith.Field{
            VerboseName : "备注",
            Name        : "Remark",
            Column      : "remark",
            FieldType   : fieldtype.NVarchar,
            Length      : 500,
            Precision   : 0,
            Scale       : 0,
            Unique      : "false",
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "3",
            Max         : "250",
        },
    },
}
