package inventory

import (
    "matrix/smith"
    "matrix/smith/fieldtype"
)

var StorageLocEntity = smith.Entity{
    ModuleTitleName     : "Inventory",
    ModuleLowerCase     : "inventory",
    ModuleChinese       : "库存管理",
    EntityTitleName     : "StorageLoc",
    EntityCamelCase     : "storageLoc",
    EntityChinese       : "库位",
    TableName           : "storage_loc",
    TablePrefix         : "hd_inventory_",

    FieldList: []smith.Field{
        smith.Field{
            VerboseName : "编号",
            Name        : "Code",
            Column      : "stock_code",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : "code",
            Index       : false,
            Null        : false,
            Blank       : false,
            Min         : "3",
            Max         : "10",
        },
        smith.Field{
            VerboseName : "名称",
            Name        : "Name",
            Column      : "stock_name",
            FieldType   : fieldtype.NVarchar,
            Length      : 255,
            Precision   : 0,
            Scale       : 0,
            Unique      : "name",
            Index       : false,
            Null        : false,
            Blank       : false,
            Min         : "3",
            Max         : "30",
        },
        smith.Field{
            VerboseName : "仓库",
            Name        : "StockId",
            Column      : "stock_id",
            FieldType   : fieldtype.BigInt,
            Length      : 0,
            Precision   : 0,
            Scale       : 0,
            Unique      : "code, name",
            Index       : true,
            Null        : false,
            Blank       : false,
            Min         : "",
            Max         : "",
        },
        smith.Field{
            VerboseName : "备注",
            Name        : "Remark",
            Column      : "remark",
            FieldType   : fieldtype.NVarchar,
            Length      : 500,
            Precision   : 0,
            Scale       : 0,
            Unique      : "false",
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "3",
            Max         : "250",
        },
    },
}
