package inventory

import (
    "matrix/smith"
    "matrix/smith/fieldtype"
)

var SupplierEntity = smith.Entity{
    ModuleTitleName     : "Inventory",
    ModuleLowerCase     : "inventory",
    ModuleChinese       : "库存管理",
    EntityTitleName     : "Supplier",
    EntityLowerCase     : "supplier",
    EntityChinese       : "供应商",
    TableName           : "supplier",
    TablePrefix         : "hd_inventory_",

    FieldList: []smith.Field{
        smith.Field{
            VerboseName : "供应商名称",
            Name        : "Name",
            Column      : "sup_name",
            FieldType   : fieldtype.NVarchar,
            Length      : 255,
            Precision   : 0,
            Scale       : 0,
            Unique      : true,
            Index       : true,
            Null        : false,
            Blank       : false,
            Min         : "3",
            Max         : "30",
        },
        smith.Field{
            VerboseName : "供应商编号",
            Name        : "Code",
            Column      : "sup_code",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : true,
            Index       : true,
            Null        : false,
            Blank       : false,
            Min         : "3",
            Max         : "10",
        },
        smith.Field{
            VerboseName : "联系人",
            Name        : "Contact",
            Column      : "contact",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : false,
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "",
            Max         : "20",
        },
        smith.Field{
            VerboseName : "联系电话",
            Name        : "Phone",
            Column      : "phone",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : false,
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "2",
            Max         : "40",
        },
        smith.Field{
            VerboseName : "联系地址",
            Name        : "Address",
            Column      : "address",
            FieldType   : fieldtype.NVarchar,
            Length      : 300,
            Precision   : 0,
            Scale       : 0,
            Unique      : false,
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "3",
            Max         : "20",
        },
        smith.Field{
            VerboseName : "开户银行",
            Name        : "Bank",
            Column      : "bank",
            FieldType   : fieldtype.NVarchar,
            Length      : 255,
            Precision   : 0,
            Scale       : 0,
            Unique      : false,
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "",
            Max         : "20",
        },
        smith.Field{
            VerboseName : "银行账号",
            Name        : "BankAccount",
            Column      : "bank_account",
            FieldType   : fieldtype.NVarchar,
            Length      : 100,
            Precision   : 0,
            Scale       : 0,
            Unique      : false,
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "4",
            Max         : "50",
        },
        smith.Field{
            VerboseName : "备注",
            Name        : "Remark",
            Column      : "remark",
            FieldType   : fieldtype.NVarchar,
            Length      : 500,
            Precision   : 0,
            Scale       : 0,
            Unique      : false,
            Index       : false,
            Null        : true,
            Blank       : true,
            Min         : "3",
            Max         : "250",
        },
    },
}
